---
- name: Initial setup.
  hosts: all
  become: true
  vars:
    regular_user: "christophe"

  tasks:
  - name: Update default password.
    user: 
      name: "{{ regular_user }}"
      update_password: always 
      password: "{{ newpassword|password_hash('sha512') }}"