---
k3s_version: v1.22.3+k3s1
ansible_user: christophe
systemd_dir: /etc/systemd/system
chief_ip: "{{ hostvars[groups['chiefs'][0]]['ansible_host'] | default(groups['chiefs'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
k3s_server_location: /var/lib/rancher/k3s